### ISSUE TITLE
vue3 defineExpose无法正常使用

### ISSUE THREAD

**Issue by star9923** [au1996/vue3-element-admin-ts#6]
## Bug report（问题描述）
vue3提供api defineExpose无法正常使用

#### Steps to reproduce（问题复现步骤）

<template>
</template>

<script setup>
import {
  defineExpose
} from 'vue';
defineExpose({
  a: '测试'
})
</script>

#### Other relevant information（格外信息）

- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by au1996** [comment]
将vue的版本从 `3.2.2` 升级至 `3.2.13` 及以上版本； 即可解决此`BUG`
